%%main
clc; clear all; close all;
numberOfTrainCases = 100;


imaqhwinfo
obj = videoinput('winvideo');
%%obj = videoinput('winvideo',1,'YUY2_320x240');
%%preview( src );
set(obj, 'FramesPerTrigger', 1);
set(obj, 'TriggerRepeat', Inf);
%%start(obj);
a = arduino('com3','Uno');
configureDigitalPin(a,6,'pullup');
writeDigitalPin(a, 9, 0);
writeDigitalPin(a, 10, 0);

%定义一个监控界面
hf = figure('Units', 'Normalized', 'Menubar', 'None','NumberTitle', 'off', 'Name', 'Real Time Capture');
ha = axes('Parent', hf, 'Units', 'Normalized', 'Position', [0.05 0.2 0.65 0.7]);
axis off

%定义3个按钮控件
hb1 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.00 0.05 0.15 0.1], 'String', 'On', 'Callback', ...
    ['objRes = get(obj, ''VideoResolution'');' ...
     'nBands = get(obj, ''NumberOfBands'');' ...
     'hImage = image(zeros(objRes(2), objRes(1), nBands));' ...
     'preview(obj, hImage);']);
%hb2 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.05 0.05 0.05 0.1], 'String', 'Off', 'Callback', ...
%    ['stop(obj);']); 
%hb3 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.10 0.05 0.05 0.1], 'String', 'Del', 'Callback', ...
%    ['delete(obj);']);
hb401 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.6 0.15 0.1], 'String', 'SnapObj1', 'Callback', ...
    'imTrainSnapshot(obj,a,1,numberOfTrainCases);');
hb402 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.5 0.15 0.1], 'String', 'SnapObj2', 'Callback', ...
    'imTrainSnapshot(obj,a,2,numberOfTrainCases);');
hb403 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.4 0.15 0.1], 'String', 'SnapObj3', 'Callback', ...
    'imTrainSnapshot(obj,a,3,numberOfTrainCases);');
hb404 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.3 0.15 0.1], 'String', 'SnapOthers', 'Callback', ...
    'imTrainSnapshot(obj,a,0,numberOfTrainCases);');
hb5 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.30 0.05 0.15 0.1], 'String', 'Train', 'Callback', ...
    '[net,inputn,inputps,outputn,outputps] = Imtrain01()'); %train the cases
%hb5 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.75 0.05 0.2 0.1], 'String', 'Identify', 'Callback', ...
%    ['[W1,WB1] = Classify(''C:\\MATLAB\\SupportPackages\\R2014a\\arduinoio\\im.jpg'');' ...
%     '[ object , similarity ] = imIdentify( WB1 );' ...
%     'returnError = arduinoAction(object, similarity);']); %相关性分析 
hb6 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.45 0.05 0.15 0.1], 'String', 'Identify', 'Callback', ...
    ['while(1)' ...
     'imTestSnapshot(obj,a);' ...
     'end']); %相关性分析 
hb7 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.60 0.05 0.10 0.1], 'String', 'Ob1', 'Callback', ...
    'arduinoAction(a,1);'); 
hb8 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.70 0.05 0.10 0.1], 'String', 'Ob2', 'Callback', ...
    'arduinoAction(a,2);'); 
hb9 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.05 0.10 0.1], 'String', 'Ob3', 'Callback', ...
    'arduinoAction(a,3);'); 
hb10 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.80 0.05 0.10 0.1], 'String', 'Waste', 'Callback', ...
    'arduinoAction(a,0);'); 

%hb4 = uicontrol('Parent', hf, 'Units', 'Normalized','Position', [0.75 0.05 0.2 0.1], 'String', 'Identify', 'Callback', ...
%    ['while(1)'...
%    % 'imTestSnapshot(obj,a);'...
%     '[ object , similarity ] = imIdentify( net,inputn,inputps,outputn,outputps );' ...
%     %'[  object , similarity ] = imKNN();' ...
%     'similarity'...
%     'returnError = arduinoAction(a,object, similarity);'...
%     'end']); %相关性分析 